spring.application.name=application

# Config Server
server.port=8080
server.servlet.context-path=/api


# ==================== Definições do MySQL ====================
spring.datasource.url=jdbc:mysql://localhost:3306/probend_db?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==================== JPA, Hibernate ====================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==================== H2 para testes  ====================
# ==================== H2 para testes ====================
# # Configuração do H2
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# # Habilita o console para ver o banco
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2/console
# spring.h2.console.settings.web-allow-others=true

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

