spring.application.name=application

# Config Server
server.port=8080
server.servlet.context-path=/api


# ==================== Definições do MySQL ====================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:probend_db}?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true

# Definições usadas antes da adequação ao modelo do docker:
# spring.datasource.url=jdbc:mysql://localhost:3306/probend_db?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true

# ==================== Spring e Docker ====================
# Placeholders spring e jwt
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:1234}
jwt.secret=${JWT_SECRET:ChavePadraoParaDesenvolvimentoApenas}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Para assegurar que o spring-devtools funcione (live reload, hot reload)
spring.devtools.restart.enabled=true

# ==================== Gemini API ====================
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=${GEMINI_MODEL:gemini-3.5-flash}

# ==================== AWS S3 (MinIO) ====================
# Configurações do S3 para conexão local (MinIO)
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadminpassword}
minio.bucket-name=probend-imagens

# ==================== Spring Boot Actuator ====================
# Expõe todos os endpoints do actuator (health, metrics, env, etc)
# Usado pelo VSCode no "testing", é uma dashboard de monitoramento HTTP
# dá pra ser acessado pelo navegador
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.jmx.enabled=true


# ==================== JPA, Hibernate ====================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==================== H2 para testes  ====================
# ==================== H2 para testes ====================
# # Configuração do H2
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# # Habilita o console para ver o banco
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2/console
# spring.h2.console.settings.web-allow-others=true

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true